// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'screens/offerRide/models/location.dart';
import 'screens/offerRide/models/ride_offer.dart';
import 'screens/profile/models/user_profile.dart';
import 'screens/wallet/models/wallet_balance.dart';
import 'screens/wallet/models/wallet_transaction.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 7027434267507269485),
      name: 'Location',
      lastPropertyId: const obx_int.IdUid(8, 5098411677319176080),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 4592894167065833675),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 3799701622443345766),
            name: 'latitude',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 5582381950345498009),
            name: 'longitude',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 4099493474036263428),
            name: 'address',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 5603384658397001722),
            name: 'city',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 6365883484189651592),
            name: 'country',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 6689910268872050347),
            name: 'isDeparture',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 5098411677319176080),
            name: 'createdAt',
            type: 10,
            flags: 8,
            indexId: const obx_int.IdUid(1, 8375028642304164987))
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(2, 2952514429372149847),
      name: 'RideOffer',
      lastPropertyId: const obx_int.IdUid(16, 5455907999534103885),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 2376060431977909024),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 2336104575359050522),
            name: 'departureLat',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 255059376219021996),
            name: 'departureLng',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 3178864270068061554),
            name: 'destinationLat',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 1102553123676652503),
            name: 'destinationLng',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 4920240132591212075),
            name: 'from',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 9069432423137568416),
            name: 'to',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 5125072493044826262),
            name: 'dateTime',
            type: 10,
            flags: 8,
            indexId: const obx_int.IdUid(2, 6367058901361562702)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 3466995751616172525),
            name: 'availableSeats',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 5340081576551149724),
            name: 'price',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(11, 6534060171361344552),
            name: 'description',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(12, 5820776593353759286),
            name: 'createdAt',
            type: 10,
            flags: 8,
            indexId: const obx_int.IdUid(3, 477297220318915487)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(13, 7392615715792204974),
            name: 'driverName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(14, 6491985399024281136),
            name: 'driverId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(15, 2179086017587896300),
            name: 'vehicleInfo',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(16, 5455907999534103885),
            name: 'isActive',
            type: 1,
            flags: 8,
            indexId: const obx_int.IdUid(4, 682870673175232116))
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(3, 7015521020507013135),
      name: 'UserProfile',
      lastPropertyId: const obx_int.IdUid(15, 4333117446053075055),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 6713263157646582868),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 915147883494439490),
            name: 'userId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 5967573162891879223),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 207584510669086079),
            name: 'email',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 5829136283731079715),
            name: 'phone',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 8763408967394642617),
            name: 'bio',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 1676564742345896168),
            name: 'profileImageUrl',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 953472046321755433),
            name: 'createdAtTimestamp',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 372241672962909529),
            name: 'ridesOffered',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 2364796890377538354),
            name: 'ridesTaken',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(11, 5248602872016811621),
            name: 'rating',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(12, 3593465494061984158),
            name: 'rideNotifications',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(13, 4320657127011586534),
            name: 'chatNotifications',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(14, 3959828320454289423),
            name: 'emailNotifications',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(15, 4333117446053075055),
            name: 'createdAt',
            type: 10,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(4, 9009397057325655044),
      name: 'WalletBalance',
      lastPropertyId: const obx_int.IdUid(10, 6270782141272470632),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 6511690648026436864),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 5856654544698198230),
            name: 'userId',
            type: 9,
            flags: 2048,
            indexId: const obx_int.IdUid(5, 2267542533610752386)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 6470032596804821122),
            name: 'availableBalance',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 4006526873687471184),
            name: 'pendingBalance',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 2852409565030797456),
            name: 'totalBalance',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 2018417979192642073),
            name: 'lastUpdated',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 636054847145401117),
            name: 'createdAt',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 3474634863035950171),
            name: 'currency',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 4454973195201076478),
            name: 'isActive',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 6270782141272470632),
            name: 'isFrozen',
            type: 1,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(5, 4040997814787253175),
      name: 'WalletTransaction',
      lastPropertyId: const obx_int.IdUid(15, 2022917438102400322),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 8815129717624048023),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 3311037157489202225),
            name: 'userId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 2662504802199985372),
            name: 'amount',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 8804275835718515750),
            name: 'type',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 4145238295865688103),
            name: 'description',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 1148458959062356786),
            name: 'status',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 3317589957053302885),
            name: 'createdAt',
            type: 10,
            flags: 8,
            indexId: const obx_int.IdUid(6, 1119642909420468569)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 8621899989213159305),
            name: 'completedAt',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 7545717945539636120),
            name: 'rideId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 5763979383276140083),
            name: 'paymentMethod',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(11, 3630447607532963250),
            name: 'transactionId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(12, 7267998569419956255),
            name: 'reference',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(13, 2965681924485524455),
            name: 'fromLocation',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(14, 2358917781456495502),
            name: 'toLocation',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(15, 2022917438102400322),
            name: 'driverName',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(5, 4040997814787253175),
      lastIndexId: const obx_int.IdUid(6, 1119642909420468569),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    Location: obx_int.EntityDefinition<Location>(
        model: _entities[0],
        toOneRelations: (Location object) => [],
        toManyRelations: (Location object) => {},
        getId: (Location object) => object.id,
        setId: (Location object, int id) {
          object.id = id;
        },
        objectToFB: (Location object, fb.Builder fbb) {
          final addressOffset = fbb.writeString(object.address);
          final cityOffset =
              object.city == null ? null : fbb.writeString(object.city!);
          final countryOffset =
              object.country == null ? null : fbb.writeString(object.country!);
          fbb.startTable(9);
          fbb.addInt64(0, object.id);
          fbb.addFloat64(1, object.latitude);
          fbb.addFloat64(2, object.longitude);
          fbb.addOffset(3, addressOffset);
          fbb.addOffset(4, cityOffset);
          fbb.addOffset(5, countryOffset);
          fbb.addBool(6, object.isDeparture);
          fbb.addInt64(7, object.createdAt.millisecondsSinceEpoch);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = Location()
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..latitude =
                const fb.Float64Reader().vTableGet(buffer, rootOffset, 6, 0)
            ..longitude =
                const fb.Float64Reader().vTableGet(buffer, rootOffset, 8, 0)
            ..address = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 10, '')
            ..city = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 12)
            ..country = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 14)
            ..isDeparture =
                const fb.BoolReader().vTableGet(buffer, rootOffset, 16, false)
            ..createdAt = DateTime.fromMillisecondsSinceEpoch(
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0));

          return object;
        }),
    RideOffer: obx_int.EntityDefinition<RideOffer>(
        model: _entities[1],
        toOneRelations: (RideOffer object) => [],
        toManyRelations: (RideOffer object) => {},
        getId: (RideOffer object) => object.id,
        setId: (RideOffer object, int id) {
          object.id = id;
        },
        objectToFB: (RideOffer object, fb.Builder fbb) {
          final fromOffset = fbb.writeString(object.from);
          final toOffset = fbb.writeString(object.to);
          final descriptionOffset = fbb.writeString(object.description);
          final driverNameOffset = object.driverName == null
              ? null
              : fbb.writeString(object.driverName!);
          final driverIdOffset = object.driverId == null
              ? null
              : fbb.writeString(object.driverId!);
          final vehicleInfoOffset = object.vehicleInfo == null
              ? null
              : fbb.writeString(object.vehicleInfo!);
          fbb.startTable(17);
          fbb.addInt64(0, object.id);
          fbb.addFloat64(1, object.departureLat);
          fbb.addFloat64(2, object.departureLng);
          fbb.addFloat64(3, object.destinationLat);
          fbb.addFloat64(4, object.destinationLng);
          fbb.addOffset(5, fromOffset);
          fbb.addOffset(6, toOffset);
          fbb.addInt64(7, object.dateTime.millisecondsSinceEpoch);
          fbb.addInt64(8, object.availableSeats);
          fbb.addFloat64(9, object.price);
          fbb.addOffset(10, descriptionOffset);
          fbb.addInt64(11, object.createdAt.millisecondsSinceEpoch);
          fbb.addOffset(12, driverNameOffset);
          fbb.addOffset(13, driverIdOffset);
          fbb.addOffset(14, vehicleInfoOffset);
          fbb.addBool(15, object.isActive);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final departureLatParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 6, 0);
          final departureLngParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 8, 0);
          final destinationLatParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 10, 0);
          final destinationLngParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 12, 0);
          final fromParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 14, '');
          final toParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 16, '');
          final dateTimeParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0));
          final availableSeatsParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0);
          final priceParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 22, 0);
          final descriptionParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 24, '');
          final driverNameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 28);
          final driverIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 30);
          final vehicleInfoParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 32);
          final isActiveParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 34, false);
          final object = RideOffer(
              departureLat: departureLatParam,
              departureLng: departureLngParam,
              destinationLat: destinationLatParam,
              destinationLng: destinationLngParam,
              from: fromParam,
              to: toParam,
              dateTime: dateTimeParam,
              availableSeats: availableSeatsParam,
              price: priceParam,
              description: descriptionParam,
              driverName: driverNameParam,
              driverId: driverIdParam,
              vehicleInfo: vehicleInfoParam,
              isActive: isActiveParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..createdAt = DateTime.fromMillisecondsSinceEpoch(
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 26, 0));

          return object;
        }),
    UserProfile: obx_int.EntityDefinition<UserProfile>(
        model: _entities[2],
        toOneRelations: (UserProfile object) => [],
        toManyRelations: (UserProfile object) => {},
        getId: (UserProfile object) => object.id,
        setId: (UserProfile object, int id) {
          object.id = id;
        },
        objectToFB: (UserProfile object, fb.Builder fbb) {
          final userIdOffset = fbb.writeString(object.userId);
          final nameOffset = fbb.writeString(object.name);
          final emailOffset = fbb.writeString(object.email);
          final phoneOffset = fbb.writeString(object.phone);
          final bioOffset = fbb.writeString(object.bio);
          final profileImageUrlOffset = object.profileImageUrl == null
              ? null
              : fbb.writeString(object.profileImageUrl!);
          fbb.startTable(16);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, userIdOffset);
          fbb.addOffset(2, nameOffset);
          fbb.addOffset(3, emailOffset);
          fbb.addOffset(4, phoneOffset);
          fbb.addOffset(5, bioOffset);
          fbb.addOffset(6, profileImageUrlOffset);
          fbb.addInt64(7, object.createdAtTimestamp);
          fbb.addInt64(8, object.ridesOffered);
          fbb.addInt64(9, object.ridesTaken);
          fbb.addFloat64(10, object.rating);
          fbb.addBool(11, object.rideNotifications);
          fbb.addBool(12, object.chatNotifications);
          fbb.addBool(13, object.emailNotifications);
          fbb.addInt64(14, object.createdAt.millisecondsSinceEpoch);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final userIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final emailParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 10, '');
          final phoneParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 12, '');
          final bioParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 14, '');
          final profileImageUrlParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 16);
          final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 32, 0));
          final ridesOfferedParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0);
          final ridesTakenParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 22, 0);
          final ratingParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 24, 0);
          final rideNotificationsParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 26, false);
          final chatNotificationsParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 28, false);
          final emailNotificationsParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 30, false);
          final object = UserProfile(
              id: idParam,
              userId: userIdParam,
              name: nameParam,
              email: emailParam,
              phone: phoneParam,
              bio: bioParam,
              profileImageUrl: profileImageUrlParam,
              createdAt: createdAtParam,
              ridesOffered: ridesOfferedParam,
              ridesTaken: ridesTakenParam,
              rating: ratingParam,
              rideNotifications: rideNotificationsParam,
              chatNotifications: chatNotificationsParam,
              emailNotifications: emailNotificationsParam)
            ..createdAtTimestamp =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0);

          return object;
        }),
    WalletBalance: obx_int.EntityDefinition<WalletBalance>(
        model: _entities[3],
        toOneRelations: (WalletBalance object) => [],
        toManyRelations: (WalletBalance object) => {},
        getId: (WalletBalance object) => object.id,
        setId: (WalletBalance object, int id) {
          object.id = id;
        },
        objectToFB: (WalletBalance object, fb.Builder fbb) {
          final userIdOffset = fbb.writeString(object.userId);
          final currencyOffset = fbb.writeString(object.currency);
          fbb.startTable(11);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, userIdOffset);
          fbb.addFloat64(2, object.availableBalance);
          fbb.addFloat64(3, object.pendingBalance);
          fbb.addFloat64(4, object.totalBalance);
          fbb.addInt64(5, object.lastUpdated.millisecondsSinceEpoch);
          fbb.addInt64(6, object.createdAt.millisecondsSinceEpoch);
          fbb.addOffset(7, currencyOffset);
          fbb.addBool(8, object.isActive);
          fbb.addBool(9, object.isFrozen);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final userIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final availableBalanceParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 8, 0);
          final pendingBalanceParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 10, 0);
          final currencyParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 18, '');
          final isActiveParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 20, false);
          final isFrozenParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 22, false);
          final object = WalletBalance(
              userId: userIdParam,
              availableBalance: availableBalanceParam,
              pendingBalance: pendingBalanceParam,
              currency: currencyParam,
              isActive: isActiveParam,
              isFrozen: isFrozenParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..totalBalance =
                const fb.Float64Reader().vTableGet(buffer, rootOffset, 12, 0)
            ..lastUpdated = DateTime.fromMillisecondsSinceEpoch(
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0))
            ..createdAt = DateTime.fromMillisecondsSinceEpoch(
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0));

          return object;
        }),
    WalletTransaction: obx_int.EntityDefinition<WalletTransaction>(
        model: _entities[4],
        toOneRelations: (WalletTransaction object) => [],
        toManyRelations: (WalletTransaction object) => {},
        getId: (WalletTransaction object) => object.id,
        setId: (WalletTransaction object, int id) {
          object.id = id;
        },
        objectToFB: (WalletTransaction object, fb.Builder fbb) {
          final userIdOffset = fbb.writeString(object.userId);
          final typeOffset = fbb.writeString(object.type);
          final descriptionOffset = fbb.writeString(object.description);
          final statusOffset = fbb.writeString(object.status);
          final rideIdOffset =
              object.rideId == null ? null : fbb.writeString(object.rideId!);
          final paymentMethodOffset = object.paymentMethod == null
              ? null
              : fbb.writeString(object.paymentMethod!);
          final transactionIdOffset = object.transactionId == null
              ? null
              : fbb.writeString(object.transactionId!);
          final referenceOffset = object.reference == null
              ? null
              : fbb.writeString(object.reference!);
          final fromLocationOffset = object.fromLocation == null
              ? null
              : fbb.writeString(object.fromLocation!);
          final toLocationOffset = object.toLocation == null
              ? null
              : fbb.writeString(object.toLocation!);
          final driverNameOffset = object.driverName == null
              ? null
              : fbb.writeString(object.driverName!);
          fbb.startTable(16);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, userIdOffset);
          fbb.addFloat64(2, object.amount);
          fbb.addOffset(3, typeOffset);
          fbb.addOffset(4, descriptionOffset);
          fbb.addOffset(5, statusOffset);
          fbb.addInt64(6, object.createdAt.millisecondsSinceEpoch);
          fbb.addInt64(7, object.completedAt?.millisecondsSinceEpoch);
          fbb.addOffset(8, rideIdOffset);
          fbb.addOffset(9, paymentMethodOffset);
          fbb.addOffset(10, transactionIdOffset);
          fbb.addOffset(11, referenceOffset);
          fbb.addOffset(12, fromLocationOffset);
          fbb.addOffset(13, toLocationOffset);
          fbb.addOffset(14, driverNameOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final completedAtValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 18);
          final userIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final amountParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 8, 0);
          final typeParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 10, '');
          final descriptionParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 12, '');
          final statusParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 14, '');
          final rideIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 20);
          final paymentMethodParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 22);
          final transactionIdParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 24);
          final referenceParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 26);
          final fromLocationParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 28);
          final toLocationParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 30);
          final driverNameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 32);
          final object = WalletTransaction(
              userId: userIdParam,
              amount: amountParam,
              type: typeParam,
              description: descriptionParam,
              status: statusParam,
              rideId: rideIdParam,
              paymentMethod: paymentMethodParam,
              transactionId: transactionIdParam,
              reference: referenceParam,
              fromLocation: fromLocationParam,
              toLocation: toLocationParam,
              driverName: driverNameParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..createdAt = DateTime.fromMillisecondsSinceEpoch(
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0))
            ..completedAt = completedAtValue == null
                ? null
                : DateTime.fromMillisecondsSinceEpoch(completedAtValue);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Location] entity fields to define ObjectBox queries.
class Location_ {
  /// See [Location.id].
  static final id =
      obx.QueryIntegerProperty<Location>(_entities[0].properties[0]);

  /// See [Location.latitude].
  static final latitude =
      obx.QueryDoubleProperty<Location>(_entities[0].properties[1]);

  /// See [Location.longitude].
  static final longitude =
      obx.QueryDoubleProperty<Location>(_entities[0].properties[2]);

  /// See [Location.address].
  static final address =
      obx.QueryStringProperty<Location>(_entities[0].properties[3]);

  /// See [Location.city].
  static final city =
      obx.QueryStringProperty<Location>(_entities[0].properties[4]);

  /// See [Location.country].
  static final country =
      obx.QueryStringProperty<Location>(_entities[0].properties[5]);

  /// See [Location.isDeparture].
  static final isDeparture =
      obx.QueryBooleanProperty<Location>(_entities[0].properties[6]);

  /// See [Location.createdAt].
  static final createdAt =
      obx.QueryDateProperty<Location>(_entities[0].properties[7]);
}

/// [RideOffer] entity fields to define ObjectBox queries.
class RideOffer_ {
  /// See [RideOffer.id].
  static final id =
      obx.QueryIntegerProperty<RideOffer>(_entities[1].properties[0]);

  /// See [RideOffer.departureLat].
  static final departureLat =
      obx.QueryDoubleProperty<RideOffer>(_entities[1].properties[1]);

  /// See [RideOffer.departureLng].
  static final departureLng =
      obx.QueryDoubleProperty<RideOffer>(_entities[1].properties[2]);

  /// See [RideOffer.destinationLat].
  static final destinationLat =
      obx.QueryDoubleProperty<RideOffer>(_entities[1].properties[3]);

  /// See [RideOffer.destinationLng].
  static final destinationLng =
      obx.QueryDoubleProperty<RideOffer>(_entities[1].properties[4]);

  /// See [RideOffer.from].
  static final from =
      obx.QueryStringProperty<RideOffer>(_entities[1].properties[5]);

  /// See [RideOffer.to].
  static final to =
      obx.QueryStringProperty<RideOffer>(_entities[1].properties[6]);

  /// See [RideOffer.dateTime].
  static final dateTime =
      obx.QueryDateProperty<RideOffer>(_entities[1].properties[7]);

  /// See [RideOffer.availableSeats].
  static final availableSeats =
      obx.QueryIntegerProperty<RideOffer>(_entities[1].properties[8]);

  /// See [RideOffer.price].
  static final price =
      obx.QueryDoubleProperty<RideOffer>(_entities[1].properties[9]);

  /// See [RideOffer.description].
  static final description =
      obx.QueryStringProperty<RideOffer>(_entities[1].properties[10]);

  /// See [RideOffer.createdAt].
  static final createdAt =
      obx.QueryDateProperty<RideOffer>(_entities[1].properties[11]);

  /// See [RideOffer.driverName].
  static final driverName =
      obx.QueryStringProperty<RideOffer>(_entities[1].properties[12]);

  /// See [RideOffer.driverId].
  static final driverId =
      obx.QueryStringProperty<RideOffer>(_entities[1].properties[13]);

  /// See [RideOffer.vehicleInfo].
  static final vehicleInfo =
      obx.QueryStringProperty<RideOffer>(_entities[1].properties[14]);

  /// See [RideOffer.isActive].
  static final isActive =
      obx.QueryBooleanProperty<RideOffer>(_entities[1].properties[15]);
}

/// [UserProfile] entity fields to define ObjectBox queries.
class UserProfile_ {
  /// See [UserProfile.id].
  static final id =
      obx.QueryIntegerProperty<UserProfile>(_entities[2].properties[0]);

  /// See [UserProfile.userId].
  static final userId =
      obx.QueryStringProperty<UserProfile>(_entities[2].properties[1]);

  /// See [UserProfile.name].
  static final name =
      obx.QueryStringProperty<UserProfile>(_entities[2].properties[2]);

  /// See [UserProfile.email].
  static final email =
      obx.QueryStringProperty<UserProfile>(_entities[2].properties[3]);

  /// See [UserProfile.phone].
  static final phone =
      obx.QueryStringProperty<UserProfile>(_entities[2].properties[4]);

  /// See [UserProfile.bio].
  static final bio =
      obx.QueryStringProperty<UserProfile>(_entities[2].properties[5]);

  /// See [UserProfile.profileImageUrl].
  static final profileImageUrl =
      obx.QueryStringProperty<UserProfile>(_entities[2].properties[6]);

  /// See [UserProfile.createdAtTimestamp].
  static final createdAtTimestamp =
      obx.QueryIntegerProperty<UserProfile>(_entities[2].properties[7]);

  /// See [UserProfile.ridesOffered].
  static final ridesOffered =
      obx.QueryIntegerProperty<UserProfile>(_entities[2].properties[8]);

  /// See [UserProfile.ridesTaken].
  static final ridesTaken =
      obx.QueryIntegerProperty<UserProfile>(_entities[2].properties[9]);

  /// See [UserProfile.rating].
  static final rating =
      obx.QueryDoubleProperty<UserProfile>(_entities[2].properties[10]);

  /// See [UserProfile.rideNotifications].
  static final rideNotifications =
      obx.QueryBooleanProperty<UserProfile>(_entities[2].properties[11]);

  /// See [UserProfile.chatNotifications].
  static final chatNotifications =
      obx.QueryBooleanProperty<UserProfile>(_entities[2].properties[12]);

  /// See [UserProfile.emailNotifications].
  static final emailNotifications =
      obx.QueryBooleanProperty<UserProfile>(_entities[2].properties[13]);

  /// See [UserProfile.createdAt].
  static final createdAt =
      obx.QueryDateProperty<UserProfile>(_entities[2].properties[14]);
}

/// [WalletBalance] entity fields to define ObjectBox queries.
class WalletBalance_ {
  /// See [WalletBalance.id].
  static final id =
      obx.QueryIntegerProperty<WalletBalance>(_entities[3].properties[0]);

  /// See [WalletBalance.userId].
  static final userId =
      obx.QueryStringProperty<WalletBalance>(_entities[3].properties[1]);

  /// See [WalletBalance.availableBalance].
  static final availableBalance =
      obx.QueryDoubleProperty<WalletBalance>(_entities[3].properties[2]);

  /// See [WalletBalance.pendingBalance].
  static final pendingBalance =
      obx.QueryDoubleProperty<WalletBalance>(_entities[3].properties[3]);

  /// See [WalletBalance.totalBalance].
  static final totalBalance =
      obx.QueryDoubleProperty<WalletBalance>(_entities[3].properties[4]);

  /// See [WalletBalance.lastUpdated].
  static final lastUpdated =
      obx.QueryDateProperty<WalletBalance>(_entities[3].properties[5]);

  /// See [WalletBalance.createdAt].
  static final createdAt =
      obx.QueryDateProperty<WalletBalance>(_entities[3].properties[6]);

  /// See [WalletBalance.currency].
  static final currency =
      obx.QueryStringProperty<WalletBalance>(_entities[3].properties[7]);

  /// See [WalletBalance.isActive].
  static final isActive =
      obx.QueryBooleanProperty<WalletBalance>(_entities[3].properties[8]);

  /// See [WalletBalance.isFrozen].
  static final isFrozen =
      obx.QueryBooleanProperty<WalletBalance>(_entities[3].properties[9]);
}

/// [WalletTransaction] entity fields to define ObjectBox queries.
class WalletTransaction_ {
  /// See [WalletTransaction.id].
  static final id =
      obx.QueryIntegerProperty<WalletTransaction>(_entities[4].properties[0]);

  /// See [WalletTransaction.userId].
  static final userId =
      obx.QueryStringProperty<WalletTransaction>(_entities[4].properties[1]);

  /// See [WalletTransaction.amount].
  static final amount =
      obx.QueryDoubleProperty<WalletTransaction>(_entities[4].properties[2]);

  /// See [WalletTransaction.type].
  static final type =
      obx.QueryStringProperty<WalletTransaction>(_entities[4].properties[3]);

  /// See [WalletTransaction.description].
  static final description =
      obx.QueryStringProperty<WalletTransaction>(_entities[4].properties[4]);

  /// See [WalletTransaction.status].
  static final status =
      obx.QueryStringProperty<WalletTransaction>(_entities[4].properties[5]);

  /// See [WalletTransaction.createdAt].
  static final createdAt =
      obx.QueryDateProperty<WalletTransaction>(_entities[4].properties[6]);

  /// See [WalletTransaction.completedAt].
  static final completedAt =
      obx.QueryDateProperty<WalletTransaction>(_entities[4].properties[7]);

  /// See [WalletTransaction.rideId].
  static final rideId =
      obx.QueryStringProperty<WalletTransaction>(_entities[4].properties[8]);

  /// See [WalletTransaction.paymentMethod].
  static final paymentMethod =
      obx.QueryStringProperty<WalletTransaction>(_entities[4].properties[9]);

  /// See [WalletTransaction.transactionId].
  static final transactionId =
      obx.QueryStringProperty<WalletTransaction>(_entities[4].properties[10]);

  /// See [WalletTransaction.reference].
  static final reference =
      obx.QueryStringProperty<WalletTransaction>(_entities[4].properties[11]);

  /// See [WalletTransaction.fromLocation].
  static final fromLocation =
      obx.QueryStringProperty<WalletTransaction>(_entities[4].properties[12]);

  /// See [WalletTransaction.toLocation].
  static final toLocation =
      obx.QueryStringProperty<WalletTransaction>(_entities[4].properties[13]);

  /// See [WalletTransaction.driverName].
  static final driverName =
      obx.QueryStringProperty<WalletTransaction>(_entities[4].properties[14]);
}
